version: "3.3"
services:
  loadbalancer:
    build: ./loadbalancer-dockerize/
    ports:
      - "9000:80"
    depends_on:
      - web_production
      - web_production_2
      - web_production_buy
  web_production:
    build: ./frontend-dockerize/
    ports:
      - "9001:80"
    environment:
      REACT_APP_API_URL: "aquívaurldeapi"
    depends_on:
      - api_production
  web_production_2:
    build: ./frontend-dockerize/
    ports:
      - "9002:80"
    environment:
      REACT_APP_API_URL: "aquívaurldeapi"
    depends_on:
      - api_production_2
  web_production_buy:
    build: ./frontend-dockerize/
    ports:
      - "9003:80"
    environment:
      REACT_APP_API_URL: "aquívaurldeapi"
    depends_on:
      - api_production_buy
