version: "3.3"
services:
  loadbalancer:
    build: ./loadbalancer-dockerize/
    ports:
      - "9000:80"
    depends_on:
      - web_test
      - web_test_2
      - web_test_buy
  web_test:
    build: ./frontend-dockerize/
    ports:
      - "9001:80"
    depends_on:
      - api_test
  web_test_2:
    build: ./frontend-dockerize/
    ports:
      - "9002:80"
    depends_on:
      - api_test_2
  web_test_buy:
    build: ./frontend-dockerize/
    ports:
      - "9003:80"
    depends_on:
      - api_test_buy
  api_test:
    build: ./backend-dockerize/
    ports:
      - "8997:80"
    environment:
      SERVER: "sqlserver"
      PORT: 1433
      DATABASE: "AppDbContext"
      USERNAME: "sa"
      PASSWORD: "Testing123*"
      INTEGRATED_SECURITY: "false"
      TRUST_SERVER_CERTIFICATE: "true"
    depends_on:
      - testdb
    links:
      - "testdb"
  api_test_2:
    build: ./backend-dockerize/
    ports:
      - "8998:80"
    environment:
      SERVER: "sqlserver"
      PORT: 1433
      DATABASE: "AppDbContext"
      USERNAME: "sa"
      PASSWORD: "Testing123*"
      INTEGRATED_SECURITY: "false"
      TRUST_SERVER_CERTIFICATE: "true"
    depends_on:
      - testdb
    links:
      - "testdb"
  api_test_buy:
    build: ./backend-dockerize/
    ports:
      - "8999:80"
    environment:
      SERVER: "sqlserver"
      PORT: 1433
      DATABASE: "AppDbContext"
      USERNAME: "sa"
      PASSWORD: "Testing123*"
      INTEGRATED_SECURITY: "false"
      TRUST_SERVER_CERTIFICATE: "true"
    depends_on:
      - testdb
    links:
      - "testdb"
  testdb:
    image: "mcr.microsoft.com/mssql/server"
    user: "0:0"
    hostname: "sqlserver"
    environment:
      SA_PASSWORD: "Testing123*"
      ACCEPT_EULA: "Y"
    volumes:
      - data:/var/opt/mssql/data
volumes:
  data:
